export const trackingEvents = {
  pageView: "page_view",
  landingView: "landing_view",
  uploadClick: "upload_click",
  authRequired: "auth_required",
  trialPackView: "trial_pack_view",
  toolPageView: "tool_page_view",
  uploadStarted: "upload_started",
  uploadCompleted: "upload_completed",
  previewGenerated: "preview_generated",
  previewDownloaded: "preview_downloaded",
  pricingView: "pricing_view",
  dashboardOpened: "dashboard_opened",
  cleanExportClicked: "clean_export_clicked",
  creditsPageView: "credits_page_view",
  ticketCreated: "ticket_created",
  providerFailed: "provider_failed",
  providerTimeout: "provider_timeout",
  storageError: "storage_error",
  paymentFailed: "payment_failed",
  webhookFailed: "webhook_failed",
  toolSelected: "tool_selected",
  jobStarted: "job_started",
  jobCompleted: "job_completed",
  jobFailed: "job_failed",
  signup: "signup",
  signupCompleted: "signup_completed",
  checkoutStarted: "checkout_started",
  checkoutCompleted: "checkout_completed",
  purchase: "purchase",
  creditUsed: "credit_used",
  creditsSpent: "credits_spent",
  downloadResult: "download_result",
  presetSelected: "preset_selected",
  watermarkFreeExport: "watermark_free_export",
  firstCleanExport: "first_clean_export",
  abuseBlocked: "abuse_blocked",
  rateLimited: "rate_limited"
} as const;

export type TrackingEvent = (typeof trackingEvents)[keyof typeof trackingEvents];
